### ISSUE TITLE
Anonymous access to poll

### ISSUE THREAD

**Issue by A-Hoenig** [A-Hoenig/Running#2]
in order to **provide anonymous feedback** as a **user**, I can **chose to hise my identity when answering a poll**

## Acceptance criteria:

* Crit 1: The option is in form of a checkbox
* Crit 2: The poll should be incorporated on the homepage with a message "stay tuned, new poll coming soon"
* Crit 3:Admnin expiry should be at least 3 days after current date

## Tasks:
- [ ] Update admin odule view : poll design (HTML + CSS) to inlcude date picker
- [ ] Update the website view: show "Stay tuned, new poll coming soon"
- [ ] create JS function to validate expiry date is at leaast 3 days
- [ ] creat a job to check expired polls everyday at 11:59 and hide them
- [ ] update controller function
- [ ] update unit test scripts
- [ ] test the functionality

**Comment by A-Hoenig** [comment]
This was completed
